version: '3'

services:


    redis:
      image: redis:6-alpine
      ports:
        - 6379:6379

    rabbit:
        hostname: rabbit
        image: rabbitmq:management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - 15672:15672
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    flower:
      image: mher/flower:0.9.5
      environment:
        - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672//
        - FLOWER_PORT=5555
        - FLOWER_PURGE_OFFLINE_WORKERS=10
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      ports:
        - 5555:5555
      links:
        - rabbit
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

    addition:
        image: calc-addition
        build:
            context: .
            dockerfile: ./addition/Dockerfile
        environment:
          - CELERY_RESULT_BACKEND=redis://redis:6379/0

        links:
            - rabbit
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure

    subtraction:
      image: calc-subtraction
      build:
        context: .
        dockerfile: ./subtraction/Dockerfile
      environment:
          - CELERY_RESULT_BACKEND=redis://redis:6379/0
      links:
        - rabbit
      depends_on:
        - redis
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    multiplication:
      image: calc-multiplication
      build:
        context: .
        dockerfile: ./multiplication/Dockerfile
      environment:
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      links:
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    division:
      image: calc-division
      build:
        context: .
        dockerfile: ./division/Dockerfile
      environment:
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      links:
        - rabbit
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure

    producer:
        image: calc-producer
        build:
            context: .
            dockerfile: ./producer/Dockerfile
        ports:
            - 5000:5000
        environment:
          - CELERY_RESULT_BACKEND=redis://redis:6379/0
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
    producerFastApi:
      image: producer-fastapi
      build:
        context: .
        dockerfile: ./producerFastApi/Dockerfile
      ports:
        - 5001:5001
      environment:
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

